spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbtpdev.mysql.database.azure.com:3306/defaultdb?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: alex
    password: password123+
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true